services:
  api:
    build: .
    container_name: mcp-tool
    ports:
      - "8000:8000"  # Social MCP
      - "8002:8002"  # Github MCP
    environment:
      - NODE_OPTIONS=--no-warnings
    env_file:
      - .env
    restart: unless-stopped
networks:
  app-network:
    driver: bridge